checkout: Exit success if only 'local' content is missing
The gitattribute silo=local is useful for flagging content that should
not be pushed to central storage, such as less important files or
temporary files that can be recreated.  Tracking such files can be
useful, nonetheless, for example on a scratch file system.

To better support workflows that use silo=local, silo checkout is
changed to report a warning about missing content but exit with success.
It is expected that such objects might be missing, and callers of git
silo should not fail because of it.

diff --git a/bin/git-silo b/bin/git-silo
--- a/bin/git-silo
+++ b/bin/git-silo
@@ -922,8 +922,12 @@ cmd_checkout() {
         [ -z "$path" ] && continue
         objfile=$silodir/$(sha1AsObjectPath "${sha1}")
         if ! test -e "$objfile"; then
-            printf >&2 "missing silo content: %s\n" "$path"
-            haveErr=t
+            if hasSiloAttrLabel 'local' "${path}"; then
+                printf >&2 "Warning: missing silo content with label 'local': %s\n" "$path"
+            else
+                printf >&2 "missing silo content: %s\n" "$path"
+                haveErr=t
+            fi
             continue
         fi
         mkdir -p "$(dirname "$path")"
@@ -1601,6 +1605,22 @@ sha1sAsObjectPaths() {
 sha1AsObjectPath() {
     local sha1="$1"
     echo ${sha1:0:2}/${sha1:2}
+}
+
+# hasSiloAttrLabel <label> <path>
+#
+# return true if silo attribute of <path> contains <label>.
+hasSiloAttrLabel() {
+    local label=$1
+    local path=$2
+    local attr
+    attr=$(getAttrValue "silo" "${path}")
+    case ",${attr}," in
+        *,${label},*)
+            return 0
+            ;;
+    esac
+    false
 }
 
 filterSiloAttr() {
