drop transport via scp

diff --git a/bin/git-silo b/bin/git-silo
--- a/bin/git-silo
+++ b/bin/git-silo
@@ -203,49 +203,28 @@ limit.  The suffixes 'K', 'M', 'G' can be used.
 silo.ismasterstore (default 'true'): Unless set to 'false', some destructive
 operations, such as 'purge', are not permitted.
 
-silo.scp (default unset): Tells git-silo which program to use for scp.
-
-silo.scpargstyle (default 'openssh'): Tells git-silo how to pass arguments to
-scp.  If set to 'openssh', openssh path quoting will be use.  If set to 'putty',
-arguments will be quoted as require by PuTTY's pscp.exe.  The default is
-'openssh'.  If silo.scp is set to a path that contains 'pscp', silo.scpargstyle
-will default to 'putty' and arguments will be passed as required by PuTTY's
-pscp.exe.
-
 GIT_SSH (environment variable): If set, git-silo will use the specified program
 instead of ssh.
 
-silo.sshtransport (default 'scp'): Configures how to fetch and push files via
-ssh.  'scp' indicates that scp or PuTTY's pscp.exe is used.  'sshtar' indicates
-that a standard ssh connection is used together with tar.  With 'sshcat' one
-ssh connection together with cat is used per file.
+silo.sshtransport (default 'sshcat'): Configures how to fetch and push files
+via ssh.  With 'sshcat', one ssh connection is used per file.  'sshtar'
+indicates that a single ssh connection is used together with tar, which doesn't
+work on msysgit for files of 2GB or larger..
 
 # KNOWN ISSUES
 
-  - scp performance on Windows might be poor (only 1 MB/s on local network).
+  - ssh performance on Windows might be poor (only 1 MB/s on local network).
     The reason is that openssh, which comes with msysgit, suffers from the
     problem explained in
 
         http://support.microsoft.com/kb/823764
 
-    As a workaround, install PuTTY, configure it to use pageant, and tell
-    git-silo to use pscp.exe for copying files:
-
-        git config --global silo.scp 'c:/Program Files (x86)/PuTTY/pscp.exe'
-
-    You should now see transfer rates of several 10 MB/s on a local network.
-
-  - scp in msysgit has been observed to fail during file transfer from Linux for
-    unknown reasons.  scp of the same file from a Unix machine worked.  PuTTY's
-    scp also worked.  If you experience such a problem, consider using PuTTY or
-    configuring silo to use tar to transport files (see CONFIGURATION VARIABLES
-    section):
-
-        git config --global silo.sshtransport sshtar
+    As a workaround, install PuTTY and tell git to use it (set GIT_SSH, use
+    pageant).
 
   - silo.sshtransport 'sshtar' might fail on msysgit for files of 2GB or
-    larger, because msysgit's tar does not work with large files.  Use
-    silo.transport 'sshcat' instead.
+    larger, because msysgit's tar does not work with large files.  Use the
+    default silo.transport 'sshcat' instead.
 
   - git might fail with mmap out-of-memory on Windows.  Git on Windows is a
     32-bit executable, which fails for large files in some situations.  There is
@@ -1132,144 +1111,6 @@ cmd_fetch() {
         transport_${transport}_fetch "$url"
 }
 
-# transport_scp
-transport_scp_fetch() {
-    config_ssh
-    local silodir url dir objPathMap remotep
-    local url_host url_dir
-    url=$1
-    read url_host url_dir <<< "$(parseUrl "$url")"
-    objPathMap=$(lsSiloTracked "${pathspec[@]}")
-    silodir=$(getSiloObjectDir)
-    remoteObjs=$(lsRemoteDir "$url_host" "$url_dir")
-    local areMissing=
-    while read p; do
-        [ "$p" = "" ] && continue
-        [ -f "$silodir/$p" ] && continue
-        if ! findLineIn "$p" "$remoteObjs"; then
-            areMissing=t
-            printSyncInfo "Warning: missing" "$p" "$objPathMap" >&2
-            continue
-        fi
-        printSyncInfo "Fetching" "$p" "$objPathMap"
-        remotep=$(makeScpUrl "$url_host" "$url_dir/$p")
-        if test $opt_dry_run; then
-            echo_debug "Would have run:" "$scp" "$remotep" "$silodir/$p"
-        else
-            dir="$(dirname "$p")"
-            mkdirWithParentsPermissions "$silodir/$dir"
-            echo_debug "$scp" "..."
-            rm -f "$silodir/$p-tmp"
-            # Avoid absolute local paths to work around msysgit limitation.
-            # scp d:/... would fail.
-            (
-                cd "$silodir" &&
-                exec_scp "$remotep" "$p-tmp"
-            ) || die "Failed to copy '$p'."
-
-            chmod a-w "$silodir/$p-tmp"
-            mv "$silodir/$p-tmp" "$silodir/$p"
-        fi
-    done
-    test $areMissing && die "Some files are missing at remote (see above)."
-    true
-}
-
-transport_scp_push() {
-    config_ssh
-    local silodir url objPathMap url_host url_dir existing remotep
-    url=$1
-    objPathMap=$(lsSiloTracked "${pathspec[@]}")
-    silodir=$(getSiloObjectDir)
-    read url_host url_dir <<< "$(parseUrl "$url")"
-    existing=$(lsRemoteDir "$url_host" "$url_dir")
-    while read p; do
-        [ "$p" = "" ] && continue
-        findLineIn "$p" "$existing" && continue
-        if ! [ -f "$silodir/$p" ]; then
-            printSyncInfo "Warning: missing" "$p" "$objPathMap" >&2
-            continue
-        fi
-        printSyncInfo "Pushing" "$p" "$objPathMap"
-        if test $opt_dry_run; then
-            remotep=$(makeScpUrl "$url_host" "$url_dir/$p")
-            echo_debug "Would have run:" "$scp" "$silodir/$p" "$remotep"
-        else
-            dir=$(dirname $p)
-
-            exec_ssh "$url_host" bash -s 1>&2 <<EOFPRG ||
-set -o errexit
-test -e '$url_dir/$dir' && exit 0
-if ! test -d '$url_dir'; then
-    echo "Missing silo dir '$url_dir' (run 'git-silo init' at remote to create it)."
-    exit 1
-fi
-mkdir '$url_dir/$dir'
-if test -g '$url_dir'; then
-    chmod g+ws '$url_dir/$dir'
-fi
-EOFPRG
-            die "Failed to create remote silo object subdirectory."
-
-            echo_debug "$scp" ...
-            remotep=$(makeScpUrl "$url_host" "$url_dir/$p-tmp")
-            # Avoid absolute local paths to work around msysgit limitation.
-            # scp d:/... would fail.
-	    (
-                cd "$silodir" &&
-                exec_scp "$p" "$remotep"
-	    ) || die "Failed to copy '$p'."
-
-            exec_ssh "$url_host" bash -s <<EOFPRG ||
-set -o errexit
-chmod a-w '$url_dir/$p-tmp'
-chmod g+r '$url_dir/$p-tmp'
-mv '$url_dir/$p-tmp' '$url_dir/$p'
-EOFPRG
-            die "Failed to move remote file in place."
-
-        fi
-    done
-}
-
-config_ssh() {
-    scp=$(git config silo.scp) || scp=scp
-    if ! scpargstyle=$(git config silo.scpargstyle); then
-        case "$scp" in
-        *pscp*)
-            scpargstyle=putty
-            ;;
-        *)
-            scpargstyle=openssh
-            ;;
-        esac
-    fi
-}
-
-exec_scp() {
-    local defaultargs=
-    case $scpargstyle in
-    putty)
-        defaultargs=-batch
-        ;;
-    esac
-    "$scp" $defaultargs "$@"
-}
-
-makeScpUrl() {
-    local host=$1
-    local dir=$2
-    case $scpargstyle in
-    putty)
-        printf '%s:%s' "$host" "$dir"
-        ;;
-    openssh)
-        printf '%s:"%s"' "$host" "$dir"
-        ;;
-    esac
-}
-# transport_scp
-
 # transport_sshcat
 transport_sshcat_fetch() {
     local silodir url dir objPathMap
@@ -1692,14 +1533,14 @@ getTransport() {
 
 cfg_sshtransport() {
     local o
-    o=$(git config silo.sshtransport) || o=scp
+    o=$(git config silo.sshtransport) || o=sshcat
     case ${o} in
-    sshtar|sshcat|scp)
+    sshtar|sshcat)
         echo ${o}
         ;;
     *)
-        printf "Warning: invalid option silo.sshtransport = '%s'; using 'scp'.\n" "${o}" >&2
-        echo scp
+        printf "Warning: invalid option silo.sshtransport = '%s'; using 'sshcat'.\n" "${o}" >&2
+        echo sshcat
     esac
 }
 
@@ -1802,7 +1643,7 @@ resolveGitDir() {
     localcp)
         url=$(cd "$url" && cd "$(git rev-parse --git-dir)" && pwd)
         ;;
-    scp|sshtar|sshcat)
+    sshtar|sshcat)
         read url_host url_dir <<< "$(parseUrl "$url")"
         url_dir=$(
             exec_ssh "$url_host" bash -s <<EOFPRG
