push (cp): Refuse to push to remote without silo
Instead of silently creating a missing silo dir at the remote, push (cp)
now fails in the same way as push (scp).

diff --git a/bin/git-silo b/bin/git-silo
--- a/bin/git-silo
+++ b/bin/git-silo
@@ -860,6 +860,9 @@ transport_localcp_fetch() {
 transport_localcp_push() {
     local silodir url objPathMap url_host url_dir existing
     url=$1
+    if ! [ -d "$url" ]; then
+        die "Missing silo dir '$url' (run 'git-silo init' at remote to create it)."
+    fi
     objPathMap=$(lsSiloTracked "${pathspec[@]}")
     silodir=$(getSiloObjectDir)
     while read p; do
