git-silo: Workaround Windows out of memory problem
On Windows, git-silo checkout failed with out of memory.  The hypothesis
is that git fails to load the entire fail into memory due to 32-bit
limitations.  Instead of using git to filter the file during checkout,
git-silo use cp.

diff --git a/bin/git-silo b/bin/git-silo
--- a/bin/git-silo
+++ b/bin/git-silo
@@ -344,16 +344,19 @@ cmd_add() {
 
 cmd_checkout() {
     validateHaveSilo
-    local sha1 path err
+    local sha1 path err silodir objfile
+    silodir=$(getSiloObjectDir)
     err=
     while read sha1 path; do
         [ "$path" = "" ] && continue
-        if isSha1PlaceholderFile "$path"; then
-            rm "$path"
-            git checkout -- "$path"
-            if isSha1PlaceholderFile "$path"; then
+        if ! [ -e $path ] || isSha1PlaceholderFile "$path"; then
+            objfile=$silodir/${sha1:0:2}/${sha1:2}
+            rm -f "$path"
+            echo cp ... "$path"
+            cp "$objfile" "$path" || {
+                printf >&2 "Failed to copy '%s' to '%s'.\n' "$silosha1 "$path"
                 err=t
-            fi
+            }
         fi
     done <<< "$(lsSiloTracked)"
     test $err && die "Errors during silo checkout (see above)."
