git-silo: Unify formatting of case statements
We use the official git coding style.

diff --git a/bin/git-silo b/bin/git-silo
--- a/bin/git-silo
+++ b/bin/git-silo
@@ -387,12 +387,12 @@ validateGitVersion() {
 
 validateCmd() {
     case "$1" in
-        filter_smudge|filter_clean|add|status|push|fetch|init|checkout|gc|dedup|fsck)
-            return 0
-            ;;
-        *)
-            die "Invalid command '$1'."
-            ;;
+    filter_smudge|filter_clean|add|status|push|fetch|init|checkout|gc|dedup|fsck)
+        return 0
+        ;;
+    *)
+        die "Invalid command '$1'."
+        ;;
     esac
 }
 
@@ -532,15 +532,15 @@ computeSha1AndStoreContentInSilo() {
     if [ ! -e "$objfile" ]; then
         mkdirWithParentsPermissions "$subdir"
         case $(cfg_silo_add) in
-            link)
-                ln "$arg_file" "$objfile" >/dev/null 2>&1 ||
-                cp "$arg_file" "$objfile"
-                chmod a-w "$objfile"
-                ;;
-            copy)
-                cp "$arg_file" "$objfile"
-                chmod a-w "$objfile"
-                ;;
+        link)
+            ln "$arg_file" "$objfile" >/dev/null 2>&1 ||
+            cp "$arg_file" "$objfile"
+            chmod a-w "$objfile"
+            ;;
+        copy)
+            cp "$arg_file" "$objfile"
+            chmod a-w "$objfile"
+            ;;
         esac
     fi
     printf '%s\n' $sha1
@@ -550,12 +550,12 @@ cfg_silo_add() {
     local option
     option=$(git config silo.add) || option=link
     case $option in
-        link|copy)
-            ;;  # OK
-        *)
-            printf "Warning: invalid option silo.add = '%s'; using 'link'.\n" >&2 "$option"
-            option=link
-            ;;
+    link|copy)
+        ;;  # OK
+    *)
+        printf "Warning: invalid option silo.add = '%s'; using 'link'.\n" >&2 "$option"
+        option=link
+        ;;
     esac
     echo $option
 }
@@ -922,12 +922,12 @@ config_ssh() {
     scp=$(git config silo.scp) || scp=scp
     if ! scpargstyle=$(git config silo.scpargstyle); then
         case "$scp" in
-            *pscp*)
-                scpargstyle=putty
-                ;;
-            *)
-                scpargstyle=openssh
-                ;;
+        *pscp*)
+            scpargstyle=putty
+            ;;
+        *)
+            scpargstyle=openssh
+            ;;
         esac
     fi
 }
@@ -935,9 +935,9 @@ config_ssh() {
 exec_scp() {
     local defaultargs=
     case $scpargstyle in
-        putty)
-            defaultargs=-batch
-            ;;
+    putty)
+        defaultargs=-batch
+        ;;
     esac
     "$scp" $defaultargs "$@"
 }
@@ -946,9 +946,9 @@ exec_ssh() {
     local defaultargs=
     local ssh=${GIT_SSH:-ssh}
     case "$ssh" in
-        *plink*)
-            defaultargs=-batch
-            ;;
+    *plink*)
+        defaultargs=-batch
+        ;;
     esac
     "$ssh" $defaultargs "$@"
 }
@@ -957,12 +957,12 @@ makeScpUrl() {
     local host=$1
     local dir=$2
     case $scpargstyle in
-        putty)
-            printf '%s:%s' "$host" "$dir"
-            ;;
-        openssh)
-            printf '%s:"%s"' "$host" "$dir"
-            ;;
+    putty)
+        printf '%s:%s' "$host" "$dir"
+        ;;
+    openssh)
+        printf '%s:"%s"' "$host" "$dir"
+        ;;
     esac
 }
 
@@ -1103,22 +1103,22 @@ resolveGitDir() {
     local url=$1
     local url_host url_dir
     case $(getTransport "$url") in
-        localcp)
-            url=$(cd "$url" && cd "$(git rev-parse --git-dir)" && pwd)
-            ;;
-        scp)
-            read url_host url_dir <<< "$(parseUrl "$url")"
-            url_dir=$(
-                exec_ssh "$url_host" bash -s <<EOFPRG
+    localcp)
+        url=$(cd "$url" && cd "$(git rev-parse --git-dir)" && pwd)
+        ;;
+    scp)
+        read url_host url_dir <<< "$(parseUrl "$url")"
+        url_dir=$(
+            exec_ssh "$url_host" bash -s <<EOFPRG
 set -o errexit
 test -e '$url_dir'
 cd '$url_dir'
 cd "\$(git rev-parse --git-dir)"
 pwd
 EOFPRG
-            )
-            url=$url_host:$url_dir
-            ;;
+        )
+        url=$url_host:$url_dir
+        ;;
     esac
     printf '%s' "$url"
 }
