checkout --link: work around strange behavior of msysgit's bash
This adds a workaround for the problem described below.  When using
a hardlink during checkout, git-silo now ensures that the write
permissions are unset.  If it cannot fix the permissions, it falls back
to copying.

In msysgit's bash,

    touch a
    chmod a-w a
    ln a b
    rm b

unexpectedly gives 'a' write permissions.  Unlinking a files apparently
changes the permissions of the file.

diff --git a/bin/git-silo b/bin/git-silo
--- a/bin/git-silo
+++ b/bin/git-silo
@@ -507,13 +507,21 @@ cmd_checkout() {
                 err=t
                 continue
             fi
-            rm -f "$path"
             mkdir -p "$(dirname "$path")"
             (
                 ! test $opt_copy &&
-                ln "$objfile" "$path" >/dev/null 2>&1 &&
+                rm -f "$path" &&
+                ln "$objfile" "$path" >/dev/null 2>&1 && (
+                    ! test -w "$path" ||
+                    chmod a-w "$path" >/dev/null 2>&1 || (
+                        test $opt_link &&
+                        echo "Warning: failed to set read-only permissions, falling back to copy '$path'." &&
+                        false
+                    )
+                ) &&
                 echo "    LINK" $sha1 "$path"
             ) || (
+                rm -f "$path" &&
                 cp "$objfile" "$path" &&
                 chmod u+w "$path" &&
                 echo "    COPY" $sha1 "$path"
